import dotenv from 'dotenv';
import path from 'path';
import { z } from 'zod';

dotenv.config({
  path: path.join(process.cwd(), '.env'),
});


const envSchema = z.object({
  NODE_ENV: z.enum(['production', 'development', 'test']).default('development'),
  PORT: z.preprocess((val) => Number(val), z.number().default(5003)),
  SERVER_NAME: z.string().min(1, 'Server name is required'),
  SERVER_URL: z.string().min(1, 'Server URL is required'),
  BASE_URL: z.string().min(1, 'base URL is required'),
  FRONTEND_URL: z.string().min(1, 'frontend url is required'),
  MONGODB_URL: z.string().min(1, 'MongoDB connection URL is required'),
  GOOGLE_CLIENT_ID_WEB: z.string().min(1, "Google CLient ID is required"),
  GOOGLE_CLIENT_ID_ANDROID: z.string().min(1, "Google CLient ID is required"),
  GOOGLE_CLIENT_ID_IOS: z.string().min(1, "Google CLient ID is required"),
  HASH_SECRET_KEY: z.string().min(1, "hash secret key is required"),
  APP_ID: z.string().min(1, 'App ID is required'),
  APP_CERTIFICATE: z.string().min(1, 'App certificate is required'),
  ADMIN_EMAIL: z.string().email('Invalid email format for admin email').min(1, 'Admin email is required'),
  JWT_ACCESS_TOKEN_SECRET: z.string().min(1, 'Access token secret key is required'),
  JWT_ACCESS_TOKEN_EXPIRESIN: z.string().default('1d'),
  JWT_REFRESH_TOKEN_SECRET: z.string().min(1, 'Refresh token secret key is required'),
  JWT_REFRESH_TOKEN_EXPIRESIN: z.string().default('7d'),
  TWILIO_SID: z.string().min(1, 'Twilio SID is required'),
  TWILIO_AUTH_TOKEN: z.string().min(1, 'Twilio auth token is required'),
  TWILIO_PHONE_NUMBER: z.string().min(1, 'Twilio phone number is required'),
  OTP_EXPIRY_MINUTES: z.string(),
  GOOGLE_MAPS_API_KEY: z.string().min(35, 'Google Maps API key is required'),
  ADMIN_PASSWORD: z.string(),
  SERVER_SECRET: z.string(),
  CALLBACK_SECRET: z.string(),
  FIREBASE_PROJECT_ID: z.string(),
  FIREBASE_CLIENT_EMAIL: z.string(),
  FIREBASE_PRIVATE_KEY: z.string(),
  STRIPE_SECRET_KEY: z.string().min(1, 'stripe secret key is required'),
  STRIPE_WEBHOOK_SECRET: z.string().min(1, 'stripe secret key is required'),
  GMAIL_APP_USER: z.email('Invalid email format'),
  GMAIL_APP_PASSWORD: z.string().min(1, 'Gmail app password is required'),
});

const envVars = envSchema.parse(process.env);

export default {
  node_env: envVars.NODE_ENV,
  server_port: envVars.PORT,
  server_name: envVars.SERVER_NAME,
  mongodb_url: envVars.MONGODB_URL,
  frontend_url: envVars.FRONTEND_URL,
  base_url: envVars.BASE_URL,
  hash_secret_key: envVars.HASH_SECRET_KEY,
  google_client_id_web: envVars.GOOGLE_CLIENT_ID_WEB,
  google_client_id_android: envVars.GOOGLE_CLIENT_ID_ANDROID,
  google_client_id_ios: envVars.GOOGLE_CLIENT_ID_IOS,
  jwt_access_token_secret: envVars.JWT_ACCESS_TOKEN_SECRET,
  jwt_access_token_expiresin: envVars.JWT_ACCESS_TOKEN_EXPIRESIN,
  jwt_refresh_token_secret: envVars.JWT_REFRESH_TOKEN_SECRET,
  jwt_refresh_token_expiresin: envVars.JWT_REFRESH_TOKEN_EXPIRESIN,
  otp_expires_in: envVars.OTP_EXPIRY_MINUTES,
  stripe_webhook_secret: envVars.STRIPE_WEBHOOK_SECRET,
  google_maps_api_key: envVars.GOOGLE_MAPS_API_KEY,
  stripe_secret_key: envVars.STRIPE_SECRET_KEY,
  firebase_clientEmail: envVars.FIREBASE_CLIENT_EMAIL,
  firebase_projectId: envVars.FIREBASE_PROJECT_ID,
  firebase_privateKey: envVars.FIREBASE_PRIVATE_KEY,
  gmail_app_user: envVars.GMAIL_APP_USER,
  gmail_app_password: envVars.GMAIL_APP_PASSWORD,
  admin_password: envVars.ADMIN_PASSWORD,
  server_url: envVars.SERVER_URL,
  app_id: envVars.APP_ID,
  admin_email: envVars.ADMIN_EMAIL,
  twilio_sid: envVars.TWILIO_SID,
  twilio_auth_token: envVars.TWILIO_AUTH_TOKEN,
  twilio_phone_number: envVars.TWILIO_PHONE_NUMBER,
  app_certificate: envVars.APP_CERTIFICATE,
  server_secret: envVars.SERVER_SECRET,
  callback_secret: envVars.CALLBACK_SECRET,
};
